#ifndef JR_MACROS_H
#define JR_MACROS_H

#define TRUE 1
#define FALSE 0

#define LED_ON		PORTB |=(1<<PORTB5)
#define LED_OFF		PORTB &= ~(1<<PORTB5)
#define	LED_TOGGLE	PINB |= (1<<PINB5)

#define BIT_ON_IN_REG(REG, BIT_OFFSET)		REG |= (1<<BIT_OFFSET)
#define BIT_OFF_IN_REG(REG, BIT_OFFSET)		REG &= ~(1<<BIT_OFFSET)
#define BIT_FLIP_IN_REG(REG, BIT_OFFSET)	REG ^= (1<<BIT_OFFSET)

#define PIN_X_ON(PORT_REG, BIT_OFFSET)		PORT_REG |= (1<<BIT_OFFSET)
#define PIN_X_OFF(PORT_REG, BIT_OFFSET)		PORT_REG &= ~(1<<BIT_OFFSET)
#define PIN_X_TOGGLE(PIN_REG, BIT_OFFSET)	PIN_REG |= (1<<BIT_OFFSET)

#define PIN_X_INPUT(DATA_DIR_REG, BIT_OFFSET)	DATA_DIR_REG |= (1<<BIT_OFFSET)
#define PIN_X_OUTPUT(DATA_DIR_REG, BIT_OFFSET)	DATA_DIR_REG &= ~(1<<BIT_OFFSET)

#define BITS_2_ON_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2)		REG |= (1<<BIT_OFFSET1) | (1<<BIT_OFFSET2)
#define BITS_3_ON_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3)		REG |= (1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3)
#define BITS_4_ON_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4)		REG |= (1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4)
#define BITS_5_ON_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4, BIT_OFFSET5)		REG |= (1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4) | (1<<BIT_OFFSET5)
#define BITS_6_ON_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4, BIT_OFFSET5, BIT_OFFSET6)		REG |= (1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4) | (1<<BIT_OFFSET5) | (1<<BIT_OFFSET6)
#define BITS_7_ON_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4, BIT_OFFSET5, BIT_OFFSET6, BIT_OFFSET7)		REG |= (1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4) | (1<<BIT_OFFSET5) | (1<<BIT_OFFSET6) | (1<<BIT_OFFSET7)

#define BITS_2_OFF_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2)		REG &= ~(1<<BIT_OFFSET1) | (1<<BIT_OFFSET2)
#define BITS_3_OFF_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3)		REG &= ~(1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3)
#define BITS_4_OFF_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4)		REG &= ~(1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4)
#define BITS_5_OFF_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4, BIT_OFFSET5)		REG &= ~(1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4) | (1<<BIT_OFFSET5)
#define BITS_6_OFF_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4, BIT_OFFSET5, BIT_OFFSET6)		REG &= ~(1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4) | (1<<BIT_OFFSET5) | (1<<BIT_OFFSET6)
#define BITS_7_OFF_IN_REG(REG, BIT_OFFSET1, BIT_OFFSET2, BIT_OFFSET3, BIT_OFFSET4, BIT_OFFSET5, BIT_OFFSET6, BIT_OFFSET7)		REG &= ~(1<<BIT_OFFSET1) | (1<<BIT_OFFSET2) | (1<<BIT_OFFSET3) | (1<<BIT_OFFSET4) | (1<<BIT_OFFSET5) | (1<<BIT_OFFSET6) | (1<<BIT_OFFSET7)


#endif 
